### ISSUE TITLE
[deven website] Create information architecture

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#10]
# Description
Define information architecture for the DEVEN website that will reflect requirements outlined in [the proposal](https://ts.accenture.com/:w:/r/sites/DEVEN/Shared%20Documents/General/04_Wiki%20%26%C2%A0Website/DEVEN%20Wiki%20Proposal.docx?d=w0e46d83f46d34492a6850468ef0f363c&csf=1&web=1&e=wURpHV) as well as common practices, discuss it with the team and iterate if needed. 

# Acceptance Criteria

- [x] In the information architecture schema, include the following sections: About, Get started, Contributors, Blog. 
- [x] Discuss with the team what other parts should be included. 
- [x] Iterate if needed. 
- [x] Document the outcome. 

# Technical Approach
Define the information architecture in [the following Mural board](https://app.mural.co/t/accenture7572/m/accenture7572/1679410146644/7668f293da729f7e337f299b5f0907f82aaea7fc?sender=uca4275be71d3dbddcfc90096). 

# Risks

##  Related tickets

📌  #8

**Comment by zoepage** [comment]
done
