### ISSUE TITLE
[BUG] Contributors: Star element

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#106]
**Describe the bug**
The text in the star element doesn't match the design (is not correctly aligned), and the button doesn't link to the right page. 

**To Reproduce**
1. Go to the "Contributors" page.
2. Scroll down to the start element. 
3. Observe the incorrect design. 
4. Click on the "Request access" button. 

**Expected behavior**
The text needs to match the design, and the button needs to link to the right page: https://github.com/deven-org. 

**Screenshots**
Current state:
<img width="565" alt="Screenshot 2023-05-03 at 11 10 45" src="https://user-images.githubusercontent.com/118968693/235876542-e0d98dab-8dd1-4220-85f7-feac5897ee8f.png">

Expected behavior:
<img width="501" alt="Screenshot 2023-05-03 at 11 10 57" src="https://user-images.githubusercontent.com/118968693/235876555-a302df39-6a32-4cbf-bd54-f6e89e88ecfc.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by zoepage** [comment]
can not reproduce. should be fixed.
