### ISSUE TITLE
[BUG] Tools: Documentation skeleton

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#108]
**Describe the bug**
The content on the Telemetry page doesn't match the Figma prototype. 
**To Reproduce**

1. Go to "Tools"
2. Click on "Documentation skeleton"
4. Observe the incorrect content 

**Expected behavior**
The content matched the Figma prototype, specifically the Desktop - Documentation skeleton board. 

**Screenshots**
Expected outcome:
<img width="367" alt="Screenshot 2023-05-04 at 11 19 41" src="https://user-images.githubusercontent.com/118968693/236163039-fdfb6bf8-ed11-4f90-bde9-dbfad613a9fb.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by davidken91** [comment]
@GiordanaFurquim / @simondoingtingz I believe this ticket can be closed. Is this right? The Figma design has a mislabeled page called Documentation Skeleton, but I believe I developed the correct one

**Comment by remmycat** [comment]
I will close this as completed, it looks like the correct content to me.
Also, I took the liberty to slightly change the design in some cases in #142, in order to align the blog post and project content styles for consistency / make it be generated from markdown.
