### ISSUE TITLE
[deven website] "About" section

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#11]
# Description
As a user, I want to be provided with the information what DEVEN is, what its mission and vision are to understand how I can utilize the framework for maximum benefits in my project and my day to day work. 

# Acceptance Criteria

- [x] Write an opening paragraph, outlining Deven's purpose.
- [x] Include or rephrase the existing mission statement.
- [x] Include or rephrase the existing vision statement.
- [x] Include a paragraph explaining how we want to achieve our goals. 

# Technical Approach
Write all of the above-mentioned in [the following document](https://ts.accenture.com/:w:/r/sites/DEVEN/Shared%20Documents/General/04_Wiki%20%26%C2%A0Website/Website/Content/About/About%20section.docx?d=wf2ce152aa2fd4077a3b08ad7fb15f636&csf=1&web=1&e=GGLm40).

# Risks

- [ ] No risk identified

##  Related tickets

📌
📌

**Comment by zoepage** [comment]
done
