### ISSUE TITLE
[BUG] Contributors: Telemetry page

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#111]
**Describe the bug**
The text on the Telemetry page has an extra paragraph that needs to be removed. 

**To Reproduce**
1. Go to "Telemetry"
2. Scroll down to the intro. 
4. Observe the error. 

**Expected behavior**
The intro doesn't contain an extra paragraph. 

**Screenshots**
Current state:
<img width="624" alt="Screenshot 2023-04-27 at 10 11 42" src="https://user-images.githubusercontent.com/118968693/236178557-70a6e0ec-28a1-4bae-bacb-e851acd386cb.png">
<img width="503" alt="Screenshot 2023-04-27 at 10 11 54" src="https://user-images.githubusercontent.com/118968693/236178570-099502ab-c5ea-403c-a1ab-f090103f4d1b.png">

Expected outcome:
<img width="410" alt="Screenshot 2023-05-04 at 12 26 34" src="https://user-images.githubusercontent.com/118968693/236178759-adafe37b-f833-4deb-a0cc-b798fe39872e.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by remmycat** [comment]
Looks like this was done, can the issue be closed?

**Comment by davidken91** [comment]
> Looks like this was done, can the issue be closed?

Yes, this issue can be closed
