### ISSUE TITLE
[deven website] Define the website's tone of voice

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#12]
# Description
As a website editor, I want to understand the website's tone of voice so that I produce website content that uses similar language. 

# Acceptance Criteria

- [ ] A document with concrete guidelines is created. The document consists of: message architecture, examples of text, other guidlines, (use of emojis, etc.) 
- [ ] The document is reviewed by Ola. 

# Technical Approach
The tone of voice will be defined in the following document. 

# Risks

- [ ] No risk identified

##  Related tickets

📌
📌

**Comment by zoepage** [comment]
done
