### ISSUE TITLE
[deven website] 404 page

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#120]
# Description
As a website visitor, I want to receive a helpful 404 error message in case I encounter a broken link or a page that doesn't exist, so that I can understand what went wrong and be directed to other relevant pages on the website.

# Acceptance Criteria

- [ ] 1 The message includes the following:
404 Error: Page not found. Don’t you worry, though. DEVEN consists of a team of undercover ages who have embarked on a mission to find it. In the meantime, sit back, relax and enjoy a cup of coffee.
- [ ] 2 The design matches the layout of the tools pages. 

# Technical Approach

# Risks

- [ ] 1
- [ ] 2
- [ ] 3

##  Related tickets

📌

**Comment by zoepage** [comment]
done
