### ISSUE TITLE
[deven website] Content: More info on Telemetry project

### ISSUE THREAD

**Issue by remmycat** [deven-org/deven-website#146]
# Description

So far the Telemetry project page says "More info coming soon..."

This task is about adding that info, by e.g. going more in-depth on how to use the Telemetry tool, or how it was built. 

# Acceptance Criteria

- [ ] "More info coming soon..." on the telemetry project page is replaced with informative content about the project

# Technical Approach

After #142 is merged, this should be added as a new markdown document at
```
src/_includes/content/telemetry.md
```
and then get included inside `src/telemetry.njk` (use `src/documentation-skeleton.njk` as a guiding example)

##  Related tickets

📌 Same task for BO1LER Project: #147

**Comment by Jumace** [comment]
More info was added
