### ISSUE TITLE
[deven website] Content: More info on BO1LER project

### ISSUE THREAD

**Issue by remmycat** [deven-org/deven-website#147]
# Description

So far the BO1LER project page says "More info coming soon..."

This task is about adding that info, by e.g. going more in-depth on how to use the BO1LER tool, or how it was built. 

# Acceptance Criteria

- [ ] "More info coming soon..." on the BO1LER project page is replaced with informative content about the project

# Technical Approach

After #142 is merged, this should be added as a new markdown document at
```
src/_includes/content/bo1ler.md
```
and then get included inside `src/boiler.njk` (use `src/documentation-skeleton.njk` as a guiding example)

##  Related tickets

📌 Same task for Telemetry Project: #146

**Comment by Jumace** [comment]
More info was added
