### ISSUE TITLE
[deven website] Configure SCSS In The Project Dependencies

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#15]
# Description

To make sure our website is aligned with the UI prototype, we will need implement SCSS styles in our application. Officially described as “CSS with superpowers,” SCSS (or Sass) offers a way to write styles for websites with more enhanced CSS syntax.

# Acceptance Criteria

- [x] Scss is installed in our project dependencies
- [x] The config is compatible with the provided browser matrix (Chrome, Firefox, Safari and Edge).
- [x] Accessibility guidelines standards are followed and are not compromised. (AA-compliant) 

# Technical Approach

There are many paths available to you when you decide you want to start adding assets to an Eleventy project. For most projects, it’s wise to let the project’s complexity and long-term maintenance goals guide which approach you choose. Start simple and grow to the next level in complexity when the project’s requirements necessitate it!

Here are a few options in order from least complex to most complex:

1) Copy css files 
2) Use an Eleventy template
3) Eleventy custom templates _(recommended)_

You can add js and css (or even scss for Sass) as [custom template types](https://www.11ty.dev/docs/languages/custom/) in Eleventy. This means that any js and css files added to your project are processed by Eleventy.

This also (optionally) allows you to post-process the CSS (using Sass, PostCSS, or LightningCSS) or client-JavaScript (using esbuild, rollup, WebPack, etc) and write the processed content to your output folder. This also allows you to use features in your bundle code that aren’t available in web browsers, like nesting CSS, TypeScript, or JSX.

Side note: this is strictly for code that runs in a web browser. There is a [different approach](https://www.11ty.dev/docs/languages/custom/#aliasing-an-existing-template-language) if you want to use TypeScript or JSX in your Node.js JavaScript files that run as part of your build.

**Here's a great guides to get you started:**

[Example: add sass support to eleventy](https://www.11ty.dev/docs/languages/custom/#example-add-sass-support-to-eleventy)

4) Component-Driven Bundles

For the step-by-step guide on how to move forward with the chosen approach, check this [documentation](https://www.11ty.dev/docs/assets/)

# Risks

- [x] The styles could be incompatible with some browsers

##  Related tickets

📌 [Microsite design for desktop #8](https://github.com/deven-org/deven-website/issues/8)

**Comment by zoepage** [comment]
done
