### ISSUE TITLE
[deven website] Write an intro for the telemetry page

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#16]
# Description
As a visitor, I want to understand what the telemetry project is about. 

# Acceptance Criteria

- [x] Write an intro. 
- [x]  Have it reviewed by Ola.

# Technical Approach

The documentation will be written in [this document](https://ts.accenture.com/:w:/r/sites/DEVEN/Shared%20Documents/General/04_Wiki%20%26%C2%A0Website/Website/Content/Telemetry/Intro%20Page.docx?d=w38545600898f4ef2956a70a91aa73303&csf=1&web=1&e=t8oOhz).

# Risks

- [x] No risks identified

##  Related tickets

📌
📌

**Comment by zoepage** [comment]
done
