### ISSUE TITLE
[deven website] Establish a process for the blog

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#17]
# Description
...

# Acceptance Criteria

- [ ] AC one
- [ ] AC two
- [ ] AC three

# Technical Approach

# Risks

- [ ] Risk one
- [ ] Risk two
- [ ] Risk three

##  Related tickets

📌
📌

**Comment by remmycat** [comment]
This might be solved partially (technical documentation on adding a blog post) with this documentation https://github.com/deven-org/deven-website/blob/main/documentation/how-to-add-blog-posts.md

Otherwise the ticket is of course very sparse on information 😅

**Comment by Jumace** [comment]
Documentation of `how to add blog post` was updated and extended
https://github.com/deven-org/deven-website/blob/main/documentation/how-to-add-blog-posts.md
