### ISSUE TITLE
[deven website] Research imprint for the website

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#18]
# Description
As a PO, I want to understand whether the deven open-source website needs an imprint, and – if so – what information the imprint should contain to ensure that our it is compliant. 

# Acceptance Criteria

- [x] Research has been performed, and the outcome has been documented in the comments
# Risks

- [ ] The research won't be done in time, and the website will be non-compliant.

**Comment by zoepage** [comment]
imprint was added to website
