### ISSUE TITLE
[deven website] Create an imprint

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#22]
# Description
As a website user, I need to be able to find contact information for the website's support team, so that I can get help with any questions or issues I have while using the website..

# Acceptance Criteria

- [x] Prepare an imprint based on the findings specified in #18. 

# Technical Approach
Prepare the imprint in [the following document](https://ts.accenture.com/:w:/r/sites/DEVEN/Shared%20Documents/General/04_Wiki%20%26%C2%A0Website/Website/Content/Footer/Imprint.docx?d=w36127360a7914ecd991120323c722c23&csf=1&web=1&e=LQjbvx). 

# Risks

- [ ] No risks identified.

##  Related tickets

📌
📌

**Comment by zoepage** [comment]
done
