### ISSUE TITLE
[deven website] Add contributors related info to the contribution page

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#23]
# Description
As a user, I want to be able to access  a page that explains whether I can join the initiative and contribute to DEVEN's projects, so that I can further enhance them. 

# Acceptance Criteria

- [x] Prepare an opening paragraph explaining that, at the moment, the project is operated by an internal team. 
- [x] Include a link to the  GihubDEVEN org highlighting that access will granted only to internal employees. 

# Technical Approach
Prepare the text in [the following document](https://ts.accenture.com/:w:/r/sites/DEVEN/Shared%20Documents/General/04_Wiki%20%26%C2%A0Website/Website/Content/Contributors/Contributors%20page.docx?d=w97fc517bb5d843408203aa16a3c9ca67&csf=1&web=1&e=u9um1C).

# Risks

- [ ] No risks identified

##  Related tickets

📌
📌

**Comment by simondoingtingz** [comment]
@zoepage What about this one?

**Comment by zoepage** [comment]
done
