### ISSUE TITLE
[deven website] Setup linter & formatter

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#29]
# Description

Code linters analyze code statically to flag programming errors, catch bugs, stylistic errors, and suspicious constructs,[1](https://nono.ma/linter-vs-formatter#fn:linter-wikipedia) using the abstract syntax tree or AST. Code linting promotes and enforces best practices by ensuring your code matches your style guide.[2](https://nono.ma/linter-vs-formatter#fn:linter-github-clean-code-linters)

Code formatters fix style—spacing, line jumps, comments—which helps enforce programming and formatting rules that can be easily automated, which helps reduce future code diffs by delegating formatting concerns to an automatic tool rather than individual developers.

As a developer, I want to make sure that our code is structured and clean, so that we can have faster code reviews and understandable syntax. 

# Acceptance Criteria

- [ ] Define style and code guidelines
- [x] Instal dependencies of chosen linter and formatter tools
- [ ] Configure linter and formatter tools in the project dependencies 

# Technical Approach

To be defined by the Dev Team.

# Risks

- [ ] By not implementing linter and formatters in the project, the reviews and, consequently, delivery might be slowed down 

##  Related tickets

📌
📌

**Comment by GiordanaFurquim** [comment]
WIP PR: https://github.com/deven-org/deven-website/pull/36/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by zoepage** [comment]
done https://github.com/deven-org/deven-website/pull/124
