### ISSUE TITLE
[deven website] Implement Main Navigation Bar & Dropdown Menu SCSS

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#44]
# Description

As a user I want to easily navigate through the website, so that I can access the different parts directly.

# Acceptance Criteria

- [ ] Implement the animations described in the[ Figma prototype](https://www.figma.com/file/uTSmTkMlTqq7QRoplWn1Se/Microsite?node-id=23-500&t=F7zWYeRdSWOkiU5S-0) using SCSS
- [ ] The implementation supports mobile view
- [ ] Hover and active states of the navigation elements should be just in grey
- [ ] On hover, the cursor type changes to `cursor: pointer`
- [ ] When the arrow icon on the main navigation is **NOT** clicked (dropdown menu is closed), the arrow icon points down
- [ ] When the arrow icon on the main navigation is clicked (dropdown menu is opened), the arrow icon points up
- [ ] The properties, fonts and colours should follow the specifications in the Figma file mentioned above
- [ ] Test it according to the Browser Compatibility Matrix, specially paying attention to Firefox compatibility
- [ ] The implementation is compliant with basic [Web Content Accessibility Guidelines (WCAG)](https://www.w3.org/WAI/standards-guidelines/wcag/)

# Technical Approach

To be defined by the Dev Team 

# Risks

- [ ] If not implemented in time, the release date will have to be postponed

##  Related tickets

📌 [[deven website] Implement Main Navigation Bar & Dropdown Menu Component#24](https://github.com/deven-org/deven-website/issues/24)

#### Main Navigation Default State 

<img width="371" alt="Screenshot 2023-04-15 at 20 34 50" src="https://user-images.githubusercontent.com/50359290/232247549-34a3d456-d391-496c-b29c-d9c3f0c0735a.png">

#### Main Navigation Hover State 

<img width="371" alt="Screenshot 2023-04-15 at 20 36 30" src="https://user-images.githubusercontent.com/50359290/232247597-1ecdde44-d79d-459e-807f-640c0f7177af.png">

#### Main Navigation With Dropdown Menu Active

<img width="365" alt="Screenshot 2023-04-15 at 20 37 22" src="https://user-images.githubusercontent.com/50359290/232247645-3c717e47-e44b-4f07-b69a-0bbb977ea423.png">

#### Animations And Colour Guidelines

<img width="569" alt="Screenshot 2023-04-15 at 20 42 02" src="https://user-images.githubusercontent.com/50359290/232247802-7fb4b326-7eeb-40b3-b4e7-2aec4fdccca3.png">

**Comment by davidken91** [comment]
Further code refactoring may be needed for:
- Hover / active state transitions
- Splitting the stylesheets into modular files to be imported into main.scss
- Splitting the mixin scss styles into separate files such as breakpoints.scss and variables.scss
