### ISSUE TITLE
[deven website] Implement Contributors Page SCSS Styles

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#48]
# Description
 
As a user, I want to understand more about the contribution process, so that I can become a contributor

# Technical Approach

To be defined by the Dev Team
 
##  Related tickets

📌 [[deven website] Implement Contributors Page#33](https://github.com/deven-org/deven-website/issues/33)

**Comment by remmycat** [comment]
This looks done to me
