### ISSUE TITLE
[deven website] Implement Project Page Component SCSS Styles #51

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#52]
# Description

TBD

# Acceptance Criteria

- [ ] 1
- [ ] 2
- [ ] 3

# Technical Approach

To be defined by the Dev Team

# Risks

- [ ] 1
- [ ] 2
- [ ] 3

##  Related tickets

📌

**Comment by remmycat** [comment]
This seems fully implemented
