### ISSUE TITLE
[deven website] Implement Latest News Component & SCSS Styles

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#54]
# Description

As a user, I want to be able to have a preview of the latest Deven news.

# Acceptance Criteria

- [ ] Implement the `Latest News` component according to the [Figma prototype](https://www.figma.com/file/uTSmTkMlTqq7QRoplWn1Se/Microsite?node-id=0-1&t=3JJAUY8KxdyAtQuD-0) provided by the UI/UX team
- [ ] The component contain a `Blog` button, that when clicked takes the user the the `Blog Results Page`
- [ ] When clicking on one of the `Blog Post Tiles`, the user is taken to the clicked `Blog Post` 
- [ ] Test it according to the Browser Compatibility Matrix, specially paying attention to Firefox compatibility
- [ ] The component supports desktop view
- [ ] The component is compliant with [Web Content Accessibility Guidelines (WCAG)](https://www.w3.org/WAI/standards-guidelines/wcag/)

# Technical Approach

To be defined by the Dev Team

# Risks

- [ ] If not implemented in time, the version 1.1 of the website will be released without the Latest News Feature

##  Related tickets

📌 [[deven website] Implement Blog Post Tile Component#56](https://github.com/deven-org/deven-website/issues/56)

#### Latest News Component 

![Image](https://user-images.githubusercontent.com/50359290/234380945-aa48d76a-4628-4d9f-bf74-437ddac28377.png)

#### Blog button

![Image](https://user-images.githubusercontent.com/50359290/234385800-6daabd90-499a-46bd-b8d7-4d55fd4e5b96.png)

#### Blog Post Tile

![Image](https://user-images.githubusercontent.com/50359290/234385879-64ddbbd2-d8e8-4b5e-abe6-e411de08de30.png)

**Comment by remmycat** [comment]
Leftovers I could identify:
- Mobile styles
- Capping the amount of blog posts to at most 3 (less for mobile?)
- Showing the newest blog posts (sorted desc. by date)
- Blog Button
