### ISSUE TITLE
[deven website] Implement Blog Post Tile Component

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#56]
# Description

The tile (or card) is a UI element that gives the designer a way to show information in an eye catching form. As a product owner, I want the user to be able to have a preview of each blog post. 

# Acceptance Criteria

- [ ] Implement the `Blog Post Tile` component according to the [Figma prototype](https://www.figma.com/file/uTSmTkMlTqq7QRoplWn1Se/Microsite?node-id=0-1&t=3JJAUY8KxdyAtQuD-0) provided by the UI/UX team
- [ ] The tile contain a placeholder for the post preview image
- [ ] The tile contain a placeholder for the post author photo
- [ ] The tile contain a placeholder for the post author name
- [ ] The tile contain a placeholder for the blog post title 
- [ ] Test it according to the Browser Compatibility Matrix, specially paying attention to Firefox compatibility
- [ ] The component supports desktop view
- [ ] The component is compliant with [Web Content Accessibility Guidelines (WCAG)](https://www.w3.org/WAI/standards-guidelines/wcag/)

# Technical Approach

To be defined by the Dev team

# Risks

- [ ] If not implemented in time, the version 1.1 of the website will be released without the Latest News Feature
- [ ] If not implemented in time, the version 1.1 of the website will be released without the Blog Posts Page

##  Related tickets

📌 [[deven website] Implement Blog Post Page & SCSS Styles#77](https://github.com/deven-org/deven-website/issues/77)

📌 [[deven website] Implement Latest News Component & SCSS Styles#54](https://github.com/deven-org/deven-website/issues/54)

###### Blog Post Tile

![Image](https://user-images.githubusercontent.com/50359290/234385879-64ddbbd2-d8e8-4b5e-abe6-e411de08de30.png)

**Comment by remmycat** [comment]
This seems to be fully implemented
