### ISSUE TITLE
[deven website] Implement Blog Post Page Component

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#57]
# Description

TBD

# Acceptance Criteria

- [ ] 1
- [ ] 2
- [ ] 3

# Technical Approach

To be defined by the Dev team

# Risks

- [ ] 1
- [ ] 2
- [ ] 3

##  Related tickets

📌

**Comment by remmycat** [comment]
This issue seems to be a duplicate of #77 (or the other way around, but that one is where the work happened)
