### ISSUE TITLE
[deven website] Implement Documentation Skeleton Project Page Component

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#61]
# Description

# Acceptance Criteria

- [ ] 1
- [ ] 2
- [ ] 3

# Technical Approach

# Risks

- [ ] 1
- [ ] 2
- [ ] 3

##  Related tickets

📌

**Comment by remmycat** [comment]
I think this has been handled - the design was fully implemented (with a few changes we decided on)
