### ISSUE TITLE
[deven website] Microsite design for desktop

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#8]
# Description

Design a microsite for desktop based on the requirements outlined in [the proposal](https://ts.accenture.com/:w:/r/sites/DEVEN/Shared%20Documents/General/04_Wiki%20%26%C2%A0Website/DEVEN%20Wiki%20Proposal.docx?d=w0e46d83f46d34492a6850468ef0f363c&csf=1&web=1&e=1OJAJK). 

# Acceptance Criteria

- [x] **The design reflects DEVEN's visual identity.**
- [x] **The microsite is categorized into the following sections:**
- [x] > About (mission + vision)
- [x] > Get started (including about)
- [x] > Contributors
- [x] > Blog
- [x] Design specifications are documented. 

# Technical Approach

The microsite will be designed in the following [ Figma file](https://www.figma.com/file/uTSmTkMlTqq7QRoplWn1Se/Microsite?node-id=0-1&t=OO0W4Zvhxll5C1Xe-0). 

# Risks

- [ ] The design is finalized on time, which would block developement. 

##  Related tickets

📌
📌

**Comment by zoepage** [comment]
done
