### ISSUE TITLE
[deven website] Implement Blog Results Page & SCSS Styles

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#86]
# Description

As a user, I want to be able to have a preview of all Deven's blog posts.

# Acceptance Criteria

- [ ] Implement the `Blog Results Page` component according to the [Figma prototype](https://www.figma.com/file/uTSmTkMlTqq7QRoplWn1Se/Microsite?node-id=0-1&t=3JJAUY8KxdyAtQuD-0) provided by the UI/UX team
- [ ] In each posts row a maximum of 3 (three) tiles should be displayes
- [ ] When clicking on one of the `Blog Post Tiles`, the user is taken to the clicked `Blog Post` 
- [ ] Test it according to the Browser Compatibility Matrix, specially paying attention to Firefox compatibility
- [ ] The component supports desktop view
- [ ] The component is compliant with [Web Content Accessibility Guidelines (WCAG)](https://www.w3.org/WAI/standards-guidelines/wcag/)

# Technical Approach

To be defined by the Dev Team

# Risks

- [ ] If not implemented in time, the version 1.1 of the website will be released without the Blog Results Page

##  Related tickets

📌 [[deven website] Implement Blog Post Tile Component#56](https://github.com/deven-org/deven-website/issues/56)

#### Blog Results Page Component 

<img width="510" alt="Screenshot 2023-04-25 at 22 10 56" src="https://user-images.githubusercontent.com/50359290/234391868-563935fb-1c6f-4d1d-bb1d-482081a02f2d.png">

#### Blog Post Tile

![Image](https://user-images.githubusercontent.com/50359290/234385879-64ddbbd2-d8e8-4b5e-abe6-e411de08de30.png)

**Comment by remmycat** [comment]
Leftovers I saw:

- Blog posts should be sorted as newest first (desc. by date)
- On larger screens, more than 3 posts can appear per line (should be max 3)
