### ISSUE TITLE
[deven website] Configure and Integrate Github Pages into Deven's Website

### ISSUE THREAD

**Issue by GiordanaFurquim** [deven-org/deven-website#9]
# Description

GitHub Pages is a static site hosting service that takes HTML, CSS, and JavaScript files straight from a repository on GitHub, optionally runs the files through a build process, and publishes a website. GitHub Pages is also our tool of choice and to have our website live, we need to configure and integrate it in our structures.

# Acceptance Criteria

- [x] GitHub Pages is configured as a `Project site`
- [x] It doesn't contain themes. We use the option of start from scratch
- [x] The `deven-website`repo is the one used for the integration 
- [x] The `main`branch is the GitHub Pages source 
- [ ] The configuration works and the website runs bug free
- [ ] The website is live and hosted via GitHub Pages

# Technical Approach

GitHub provides a very complete documentation that could be used as a start point for the configuration and integration of GitHub Pages, such as: https://pages.github.com/ and https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages. By going through this documentation, there should be enough material to kick start the analysis and research.

# Risks

- [ ] The implementation is not finalised in time, which would block the go live 

##  Related tickets

📌 This issue contain no related tickets so far.

**Comment by zoepage** [comment]
switched from github pages to netlify and automated deployment.
