### ISSUE TITLE
[BUG] Secondary navigation: The order of the navigation items doesn't correspond with the design

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#92]
**Describe the bug**
The order of the secondary navigation items doesn't correspond with the design specified in [the Figma file](https://github.com/deven-org/deven-website/issues/93). 

**To Reproduce**
1. Open the secondary navigation by clicking at "Discover" in the main navigation. 
2. Check the navigation items. 
3. Observe the error. 

**Expected behavior**
The "Team" and "Last News" navigation items needs to be swapped. 

**Screenshots**
Current state:
<img width="360" alt="Current state" src="https://user-images.githubusercontent.com/118968693/234831031-e1ebc1e5-2a43-4a6b-8a11-f77707328e27.png">
Expected behavior: 
<img width="227" alt="Design – Expected behavior" src="https://user-images.githubusercontent.com/118968693/234831028-35118e94-d7e6-4033-869b-edf57f9de368.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by remmycat** [comment]
Looks like this was implemented, can the issue be closed?
