### ISSUE TITLE
[BUG] Secondary navigation: The shape of the elelement doesn't correspond with the design.

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#93]
**Describe the bug**
Currently, the shape of the secondary navigation doesn't correspond with the design specified in the [Figma file](https://www.figma.com/file/uTSmTkMlTqq7QRoplWn1Se/Microsite?type=design&node-id=69%3A690&t=lnYZPjkFbyUbTJyu-1). The edges in the design are rounder. 

**To Reproduce**
1. Open the main navigation. 
2. Click on "Discover". 
3. Observe the error – different design. 

**Expected behavior**
The secondary navigation matches the design. 

**Screenshots**
Current state: 
<img width="360" alt="Current state" src="https://user-images.githubusercontent.com/118968693/234855211-440c8de8-cacd-45fb-a47f-2dcb1297ba85.png">
Expected outcome: 
<img width="227" alt="Design – Expected behavior" src="https://user-images.githubusercontent.com/118968693/234855280-740b281b-0e7a-4aea-bf17-5fce2ba2e844.png">

**Desktop (please complete the following information):**

**Comment by remmycat** [comment]
Looks like this was implemented, can the issue be closed?
