### ISSUE TITLE
[BUG] Mission and vision: Incorrect font size and padding

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#95]
**Describe the bug**
The current font size and the padding of the mission and vision texts doesn't match the [Figma prototype](https://www.figma.com/file/uTSmTkMlTqq7QRoplWn1Se/Microsite?type=design&node-id=23%3A500&t=lnYZPjkFbyUbTJyu-1). 

**To Reproduce**
1. Go to to the landing page.
2. Scroll down to the mission and vision. 
3. See the error.

**Expected behavior**
The font size and the padding match the Figma prototype. 

**Screenshots**
Current state:
<img width="1044" alt="Screenshot 2023-04-27 at 10 52 33" src="https://user-images.githubusercontent.com/118968693/234878406-4cce1f5c-6e68-4c39-8cd0-e5715cbcc6cd.png">

Expected outcome:
<img width="828" alt="Screenshot 2023-04-27 at 10 52 23" src="https://user-images.githubusercontent.com/118968693/234878428-ce2e655a-b91d-4b57-b66c-3d68520d55ae.png">

**Desktop (please complete the following information):**

**Comment by GiordanaFurquim** [comment]
Fix tested locally. ✅

![Image](https://user-images.githubusercontent.com/50359290/235672431-90d7ae55-f99a-41b7-a638-4b5fdffeaa90.png)
