### ISSUE TITLE
[BUG] Star element: Incorrect font size and text alignment 

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/deven-website#97]
**Describe the bug**
The font size and the text alignment doesn't correspond with [the Figma prototype](https://www.figma.com/file/uTSmTkMlTqq7QRoplWn1Se/Microsite?type=design&node-id=0-1&t=asukGtCLzj7k5vkp-0). 

**To Reproduce**
1. Go to the landing page.
2. Scroll down below the mission and the vision. 
3. Compare with the design. 
4. Observe the error in the start element. 

**Expected behavior**
The font size needs to be increased and ",right?" needs to be moved to a second line. 

**Screenshots**
Current state:
<img width="624" alt="Screenshot 2023-04-27 at 10 59 26" src="https://user-images.githubusercontent.com/118968693/235102760-ab9bbd7c-02c8-45bc-b3f4-dbe4cce4a665.png">

Expected outcome: 
<img width="421" alt="Screenshot 2023-04-27 at 10 59 13" src="https://user-images.githubusercontent.com/118968693/235102822-d00b1964-d4ad-4251-8765-b6d7a66c51c7.png">

**Desktop (please complete the following information):**

**Comment by davidken91** [comment]
Hey @kundan0887 I started looking at this ticket but forgot to assign it to myself. You can keep working on it, but you might find this code helpful. It seemed to work for me:
Remove this: `<text x="50%" y="53%" text-anchor="middle" fill="#000">Cool stuff, right?</text>`
And replace with this: 
`<text x="50%" y="50%" text-anchor="middle" fill="#000">
     <tspan dy="0em" x="50%">Cool stuff,</tspan>
     <tspan dy="1.3em" x="50%">right?</tspan>
</text>`
